### PR TITLE
Make sure HF download metrics work, better discoverability on Hugging Face

### PR DESCRIPTION
**Pull request by NielsRogge**
Dear authors,

I noticed your awesome repository trending on paperswithcode. I'm from Hugging Face and would like to help you make your models easier discoverable and downloadable for people :)

I see all checkpoints are present in a [single repository](https://huggingface.co/FoundationVision/var/tree/main), which means download metrics won't work. 😞 

This PR resolves that by showcasing the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/en/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin) class, which is a minimal class that allows to easily add functionalities like `from_pretrained`, `save_pretrained`, and `push_to_hub` to any custom `nn.Module`!

Similar to models in the Transformers/Diffusers library, it allows to push and reload models in the format of `safetensors` (for the weights) and a `config.json` (for the model's configuration). It also creates an automated model card, along with tags for better discoverability of your models. Usage is as follows:

```
from models.var import VARHF

model = VARHF.from_pretrained(f"nielsr/var_d16")
```
The corresponding model is here for now: https://huggingface.co/nielsr/var_d16, but I could transfer it (along with the other checkpoints) to your organization.

Here's a [notebook](https://colab.research.google.com/drive/1VQluEqscH2lp6KOl1F8LhxO5z44gGLGb?usp=sharing) regarding how I did that :)

Would you be interested in this integration?

Btw, in the demo_sample notebook, there's an easier way to download checkpoints directly from HF using the [hf_hub_download](https://huggingface.co/docs/huggingface_hub/v0.22.2/en/package_reference/file_download#huggingface_hub.hf_hub_download) method, it's as simple as this:

```python
from huggingface_hub import hf_hub_download

# download checkpoint
vae_ckpt= hf_hub_download(repo_id="FoundationVision/var", filename="vae_ch160v4096z32.pth", repo_type="model")
var_ckpt = hf_hub_download(repo_id="FoundationVision/var", filename=f"var_d{MODEL_DEPTH}.pth", repo_type="model")
```

Kind regards,

Niels
ML @ HF

### CODE REVIEW

**Comment by keyu-tian** [comment]
@NielsRogge thank you so much for your kind efforts on this integration, that would be great! We're definitely interested in making our models more accessible on HF, and we'd like to transfer checkpoints to `FoundationVision/var_d{x}`.

I'm gonna merge this PR and, i'm wondering, if you could help us merge VAR model (and VQVAE model) into the `transformers` library? This will further ease the use of VAR models for HF users. I'll be on hand to assist with that.

BTW, I'm considering simplifying the code further (by decoupling vae_local and vae_kwargs from the VAR definition). E.g., it would no longer need to store `vae_kwargs` in VAR model's HF config.

Best regards,
Keyu

**Comment by NielsRogge** [comment]
Great, thanks for merging the PR!

Would you be able to try out pushing the weights to FoundationVision/var_d{x} (as shown in the [notebook](https://colab.research.google.com/drive/1VQluEqscH2lp6KOl1F8LhxO5z44gGLGb?usp=sharing))? This ensures that you can track download metrics for the various checkpoints.

The demo_sample.ipynb can then be updated to directly leverage `from_pretrained`.

Regarding adding VAR to the Transformers library, this can be done using the [custom model guide](https://huggingface.co/docs/transformers/en/custom_models).

**Comment by NielsRogge** [comment]
Yes so basically there are 2 main ways to integrate your models with the hub:

1. Use the `PyTorchModelHubMixin` to ensure 🤗 hub integration in your custom VAR package, as shown in this PR, ensuring download metrics work and things like `from_pretrained`.
2. Make your models usable through the Transformers library, by following https://huggingface.co/docs/transformers/en/custom_models (which explains the `trust_remote_code=True` feature). For the model to be working without `trust_remote_code=True`, you indeed would need to submit a PR to Transformers for native integration.

**Comment by keyu-tian** [comment]
Got it, thanks for clarifying! So HF has these two ways to use a model. 1. requirs no PR to transformers but if we want someone can use VAR w/o trust_remote_code, or can see our VAR implementations in their local `transformers` library, we need to submit a PR. 

I'll try to do both. Really appreciate your guidance :D

**Pull request merged**
